name: screen_text_extractor
description: This plugin allows Flutter desktop apps to extract text from screen.
version: 0.1.3
homepage: https://github.com/leanflutter/screen_text_extractor

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  clipboard_watcher: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  dependency_validator: ^3.0.0

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: ScreenTextExtractorPlugin
      macos:
        pluginClass: ScreenTextExtractorPlugin
      windows:
        pluginClass: ScreenTextExtractorPlugin
