name: screen_text_extractor
description: This plugin allows Flutter desktop apps to extract text from screen.
version: 0.1.0
homepage: https://github.com/leanflutter/screen_text_extractor

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  clipboard_watcher: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: ScreenTextExtractorPlugin
      macos:
        pluginClass: ScreenTextExtractorPlugin
      windows:
        pluginClass: ScreenTextExtractorPlugin
